import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/key_bindings.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12.0

[font.normal]
family = "Rec Mono Duotone"

[window]
option_as_alt = "Both"
