dir=${HOME}/Downloads
# uncomment the following line if you are only using aria2 with rpc
# input-file=${HOME}/.aria2/aria2.session
save-session=${HOME}/.aria2/aria2.session
save-session-interval=60
# file-allocation=falloc
log /tmp/aria2.log

disable-ipv6=true
continue=true
max-concurrent-downloads=3
max-connection-per-server=10
split=10
min-split-size=5M
# apply timestamp of the remote file from the remote HTTP/FTP server
remote-time=true
# see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--stream-piece-selector
stream-piece-selector=geom

check-integrity=true
# number of "file not found" status from the remote HTTP/FTP servers allowed
max-file-not-found=5
# number of tries. 0 means unlimited
max-tries=0
# seconds to wait between retries
retry-wait=30
timeout=180

max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=200K
max-upload-limit=0

enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-port=6800
rpc-listen-all=true
check-certificate=false

# ftp
ftp-pasv=true


# BT/PT Setting
bt-require-crypto=true
follow-torrent=true
bt-save-metadata=true
bt-seed-unverified=true

seed-ratio=1
seed-time=5
