set -g default-terminal "screen-256color"
set -g default-shell $SHELL

unbind C-b
set -g prefix C-a
bind-key a send-prefix

# copy-mode use vi key-bindings space-enter c-[, c-]
setw -g mode-keys vi
set-option -g status-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# reload
bind r source-file ~/.tmux.conf

set -g history-limit 10000

#set-option -g mouse-select-pane on
#set -w -g mode-mouse on

bind-key h select-pane -L
bind-key k select-pane -U
bind-key j select-pane -D
bind-key l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind -r ^k resizep -U 15
bind -r ^j resizep -D 15
bind -r ^h resizep -L 15
bind -r ^l resizep -R 15

bind-key o resize-pane -Z
bind-key ^a last-window
bind-key m command-prompt -p "move window to:"  "swap-window -t '%%'"
bind-key > swap-window -t +1
bind-key < swap-window -t -1

if-shell "test -f ~/.tmuxline.theme" "source ~/.tmuxline.theme"

# statusline
set -g status-bg black
set -g status-fg white
set -g status-left '#S'
set -g status-right '#22T | %H:%M %Y-%m-%d'
set -g status-right-length 60
set -g status-interval 2

set-window-option -g window-status-current-bg yellow
set-window-option -g window-status-current-fg black

set -sg escape-time 0
set -g bell-action none
set -g visual-bell off

setw -g aggressive-resize on

# vim copy/paste
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g @shell_mode 'vi'
